name: Build APK

on:
  workflow_dispatch:
  push:
    paths:
      - 'OssanSnipeFlutter_project/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Change to project directory
        run: cd OssanSnipeFlutter_project

      - name: Get dependencies
        run: flutter pub get
        working-directory: OssanSnipeFlutter_project

      - name: Build Release APK
        run: flutter build apk --release
        working-directory: OssanSnipeFlutter_project

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OssanSnipeFlutter-APK
          path: OssanSnipeFlutter_project/build/app/outputs/flutter-apk/app-release.apk
